### ISSUE TITLE
Use content_tag for bbcode :html parameter

### ISSUE THREAD

**Issue by warezgibzzz** [veger/ruby-bbcode#26]
Before that, sorry for my english.
Here's an example of simple custom bbcode
```ruby
:spoiler => {
    :html_open => '
      <div class="block block-spoiler"><h2>Spoiler: %title%</h2>',
    :html_close => '</div>',
    # Ommitted for great justice
}
```
Now let's assume that the output has kinda complicated markup
```ruby
:spoiler => {
    :html_open => '
      <div class="block block-spoiler">
        <div class="header">
          <h2>Spoiler: %title%</h2>
          <div class="side pull-right">
            <ul class="buttons">
              <li>
                <a href="#" class="block-toggle-spoiler tip" title="" data-original-title="Show content">
                  <span class="icon-chevron-down"></span>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="content" style="display:none;">',
    :html_close => '</div></div>',
    # Ommitted for great justice
}
```

It feels like some pain to theme html for output, can i process html in method? For example:
```ruby
:spoiler => {
    :tag_template => spoiler_template(content, param_a),
    # Ommitted for great justice
}

# in somewhere
def spoiler_template(content, param_a)
  content_tag(:div, :class => "spoiler", :data => {:title => param_a}) do
    concat content_tag(:h2, "Spoiler")
    concat content_tag(:div, content, :class => "content")
  end
end
```
So it will be easier to theme bbcode to your taste.
The question is: Can i achieve that in current gem version somehow?

**Comment by veger** [comment]
It is not possible at the moment.
Furthermore, I do not really see the pain with the multiline <code>:html_open</code> syntax. Yes, it is larger than other tags, but who cares?

Nonetheless, I suppose it would be fairly easy to implement: Just check whether <code>:tag-template</code> is provided, and if so call it as a function with <code>content</code> as parameter and the parameters/tokens as a 'Hash' parameter.

I am not entirely sure though where these function should be placed. It would be nice for users/developers to be able to add new functions, without needing the modify the BBCode gem, so putting them in the [HTMLTemplate](https://github.com/veger/ruby-bbcode/blob/master/lib/ruby-bbcode/templates/html_template.rb) seems not a good location...

Another problem I foresee is that there might be multiple (templated) output methods, although only the [HTMLTemplate](https://github.com/veger/ruby-bbcode/blob/master/lib/ruby-bbcode/templates/html_template.rb) is available at the moment (besides the [BBCodeErrorsTemplate](https://github.com/veger/ruby-bbcode/blob/master/lib/ruby-bbcode/templates/bbcode_errors_template.rb), which shows the input annotated with errors).
Since other output methods are not fully supported yet, I suppose we could safely ignore this problem for now.

So, feel free to give it a try to implement this, if you'd like. If not, let me know and I'll give it a try when time permits.

**Comment by warezgibzzz** [comment]
Thanks for quick reply, then i will try to implement that.
I'll report back later with this reopened issue and demo (if i have any results).
