### ISSUE TITLE
Issue with [ul][li] and carrage returns

### ISSUE THREAD

**Issue by TexasNeo** [veger/ruby-bbcode#31]
The editor I am using browser side produced BBC that looks like this:
```
Et congregans omnes principes sacerdotum:
[ul]
[li]et scribas populi[/li]
[li]sciscitabatur ab eis[/li]
[li]ubi Christus nasceretur[/li]
[/ul]
At illi dixerunt In Bethlehem Judæ sic enim
```

But when parsed into HTML via RubyBBCode.to_html The HTML looks like this:
```
Et congregans omnes principes sacerdotum:<br>
<ul><br>
<li>et scribas populi</li><br>
<li>sciscitabatur ab eis</li><br>
<li>ubi Christus nasceretur</li><br>
</ul><br>
At illi dixerunt In Bethlehem Judæ sic enim 
```

Is there a way to not have carriage returns inside of ul elements generate <br>.

**Comment by almaron** [comment]
:+1:  Same thing with many other tags that should not have breaks after them (like `quote`, `code`, etc)

**Comment by veger** [comment]
This issue should be solved for all 'block elements', like lists, code, quote and videos, in most use-cases, only unsupported use-case I can think of is:
```
[ul]
[li]item [b]bold
[b][\li]
[/ul]
```

it will add the `<br />` after 'bold'. Iit would be fixable, but it increases complexity (reason why I didn't pick this up until now) even further, for a IMO (unlikely) corner-case. One could even argue that the user wanted this, why else would he add the newline after 'bold'...?

Feel free to try, otherwise I will close this issue later if no feedback is received
