### ISSUE TITLE
BUG:  Tag Shifter is too greedy

### ISSUE THREAD

**Issue by unixneo** [veger/ruby-bbcode#41]
The tag shifter is too greedy, raising an error:

```
Tag [color] must have 'color' parameter, Tag [color] must have 'color' parameter, [color] not closed, [color] not closed
```

This comes from page text with ```[COLOR-SOMETHING``` which is not a tag in the page text (was code).

Apologizes, but did not take the time to fix the tag sifter code to limit the scope of the matches.

**Comment by veger** [comment]
I am sorry to hear you have this issue.
But I am not using this gem for a long time, and can only spend minimal effort on it right now.
So small fixes, PRs, dependency issues, etc I can/will handle, but this issue seems too big, so unfortunately I won't be able to fix it.

So feel free to provide a fix and I'll look at it, and merge if it is acceptable.
